# SITE CONFIGURATION
baseurl: "/"
favicon: assets/favicon.ico                             # Icon displayed in the tab

reveal:
  transition: "slide" # none/fade/slide/convex/concave/zoom
  theme: "black" # beige/blood/league/moon/night/serif/simple/sky/solarized/white
  number: true
  numberType: "c" # "h.v" / "h/v" / "c/t"

# Slides
collections:
  people:
    output: true
    permalink: /:collection/:name
  timeline:
    output: true
    permalink: /:collection/:name
  slides:
    output: true
    permalink: /:collection/:name
  basements:
    output: true
    permalink: /:collection/:name
  assignments:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea"]

# Hacker theme
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

# USF CS
title: "CS NNN"
description: "Course Description"
author: "Your name"
google_analytics: false
due_date_format: "%a, %b %-d, %Y at %I:%M %p" # Thu, Jan 27, 2022 at 11:59 PM